= Container Adoption Boot Camp for Developers | DO720



*Course description*
Supporting the adoption of container technology through the development of container-native applications 
The Container Adoption Boot Camp for Developers (DO720) immerses you in intensive, hands-on development of container-native applications deployed on Red Hat's implementation of Kubernetes, Red Hat(R) OpenShift(R) Container Platform. As part of enrollment, you will receive one year of Red Hat Learning Subscription Standard, which gives you unlimited access to all of our courses online, plus up to five certification exams and two retakes.
This collection of courses is based on Red Hat OpenShift Container Platform 4.
*Course content summary*

* Introduction to containers, Kubernetes, and Red Hat OpenShift
* Deploy and managing applications on an OpenShift cluster
* Build and designing containerized applications for OpenShift
* Create microservice-based applications
* Develop an API gateway
* Deploy microservices to an OpenShift cluster
* Develop microservices with the Spring Boot runtime




*Audience for this course*

This course is for developers interested in adopting container technology and wanting to progress in their abilities in developing container-native applications, including microservices. Making this shift involves developing software in tight iterations so that business value can be realized sooner.


Prerequisites for this curriculum

* Become a Red Hat Certified System Administrator (RHCSA), or demonstrate equivalent experience
* Red Hat Application Development II: Implementing Microservice Architectures (DO283), or experience with Java EE development


Technology considerations
Internet access is required for this course in order to access the OpenShift shared and dedicated clusters.	


For full details, or to enroll: +
https://www.redhat.com/en/services/training/do720-container-adoption-boot-camp-for-developers
