////
Purpose
-------

Activities
------
Provide a single-line summary for each activity performed on a given day.  The
recommended format is "<summary><verb>", where "summary" is a brief description
of the activity, and "verb" is either "started", "progressed" or "completed".
This will help to capture tasks which span multiple days.

When an activity correlates with a task from the Statement of Work, try to use
the same verbiage as in the SOW to describe it.  This will greatly simplify
later reviews of this document.

Use good judgment when deciding which activities to list and which to omit.
A good starting point is to add:
- Any activity which requires 30 minutes or more to complete
- Tasks which are foundational or critical to the engagement regardless of time
  required
- Tasks which were not part of the Statement of Work but added per customer
  request

It is strongly recommended that the consultant update this part of the CER on a
daily basis to ensure all significant activity is captured.

Blockers
------
Provide a single-line summary for each blocker present in a given day.   The
recommended format is "<summary><verb>" where "summary" is a brief description
of the activity and "verb" is either "encountered", "ongoing" or "resolved".
This will help to capture the duration and impact of blockers.

Try to refrain from detailed explanations of blockers in this section.  Place
relevant details in the "Challenges" area of the CER and try to use the first
sentence of the Challenge description as the summary here.

PROTIP: Avoid duplication of effort with project status reports.  
If a delivery team elects to use the optional "Daily Journal" component in the 
CER then those updates should be used by the Project Manager to compile updates 
for the project status report. If the "Daily Journal" is not in use then 
information for the status report will be provided separately to the 
Project Manager by the Consultant/Architect(s) on the engagement. 

For more information see:  CER Best Practices - https://mojo.redhat.com/docs/DOC-1214437
and Delivering the CER - https://mojo.redhat.com/docs/DOC-1212843 

Sample
------

[cols="1,5,5",options=header]
|===
|Date
|Activities
|Blockers

// Date
| 06/05/2021

// Activities
a|
- Primary cluster deployment completed
- Automation for workload deployment started
- Image repository creation progressed
// Blockers
a|
- Groups for RBAC not defined in Active Directory discovered


// Date
| 06/06/2021

// Activities
a|
- Automation for workload deployment progressed
- Image repository creation completed

// Blockers
a|
- Groups for RBAC not defined in Active Directory resolved
- No Internet access for Satellite to pull in images from CDN discovered

|===


////

[cols="1,5,5",options=header]
|===
|Date
|Activities
|Blockers

// Date
| 09/14/2020

// Activities
a|
- Deploy Satellite 6.7

// Blockers
a|
- RHEL7 not supported for Satellite

// Date
| 09/16/2020

// Activities
a|
- Deploy Satellite 6.7
- Enable Repository RHEL 6,7 and 8
- Add location HQ and DR
- Create content view RHEL6,7 and 8
- Add proxy in satellite
- Create sync daily plan at 16 sep 2020 23:00 PM

// Blockers
a|
- Installatin satellite using connected method was failed because serrver using proxy

// Date
| 09/17/2020

// Activities
a|
- Check sync plan status, make sure all repository completed synchronize
- Publish content view RHEL6,7 and 8
- Create activation key RHEL7,RHEL7 and RHEL8 for client want join to satellite
- Config custom certificate

// Blockers
a|
- Certificate does not match for server satellite, Mr Tristan will regenerate new certificate

// Date
| 09/18/2020

// Activities
a|
- Check certificate for satellite and still issue with certificate.
// Blockers
a|
- Certificate does not match for server satellite

// Date
| 09/21/2020

// Activities
a|
- Deploy capsule DR and join to satellite
// Blockers
a|
- Need to generate new certificate for capsule DR

// Date
| 09/22/2020

// Activities
a|
- Verify and generate cert for capsule DEV
// Blockers
a|
- Capsule DEV unable connect to satellite, need to whitelist port in SBC side

// Date
| 09/23/2020

// Activities
a|
- Checking status of Capsule DEV/UAT Environment readiness
- Fixing issue with Candlepin after Package installation using foreman-maintain command
// Blockers
a|
- Candlepin service on the satellite server shows error "certificate failed verify" after run package update from foreman-maintain command. After running the foreman-maintain command, need to run the same command to Capsule server to put Satellite and Capsule in the same package version. Resolution guide from Red Hat :https://access.redhat.com/solutions/2273561

// Date
| 09/24/2020

// Activities
a|
- Checking status of Capsule DEV/UAT Environment readiness
- Fixing issue with Capsule UAT RPM database corruption when capsule unable use command yum,rpm and subscriber-manager (https://access.redhat.com/solutions/6903)
- Configure email notifications from Satellite server, in satellite status email notification already config but user dont get email, Mr.Tristan will check in internal side
- configure openscap on external capsule DEV and DR
// Blockers
a|
- 

// Date
| 09/25/2020

// Activities
a|
- Email notification from satellite server to user can be sent successfully, user able to receive email alert from satellite.
- Change katello-agent with remote execution (katello-host-tools). Katello agent is planned to be deprecated in the next satellite release hence we recommend to use remote execution
// Blockers
a|
- Cannot run remote execution using rexuser (solved) -> need to change the effective_user to root

|===
