= Prerequisites
 
== Enabling Connections from Capsule Server to Satellite Server
 
On Satellite Server, enter the following command to open the port for Capsule to Satellite communication:

[source,go]
----
# firewall-cmd --add-port="5646/tcp"

 # firewall-cmd --runtime-to-permanent
----
 
== Enabling Connections from Satellite Server and Clients to a Capsule Server
 
On the base operating system on which you want to install Capsule, enter the following command to open the ports for Satellite Server and clients communication to Capsule Server:
 
[source,go]
----
# firewall-cmd --add-port="53/udp" --add-port="53/tcp" \
--add-port="67/udp" --add-port="69/udp" \
--add-port="80/tcp" --add-port="443/tcp" \
--add-port="5000/tcp" --add-port="5647/tcp" \
--add-port="8000/tcp" --add-port="8140/tcp" \
--add-port="8443/tcp" --add-port="9090/tcp"

# firewall-cmd --runtime-to-permanent
 
----
 
== Verifying Firewall Settings
[source,go]
 ----
 # firewall-cmd --list-all
 ----
 
= Installing Capsule Server
 
== Registering to Satellite Server
To register your system to Satellite Server, complete the following steps:
[source,go]
----
# curl --insecure --output katello-ca-consumer-latest.noarch.rpm https://rhsatellite01.sbcdom.com/pub/katello-ca-consumer-latest.noarch.rpm

# yum localinstall katello-ca-consumer-latest.noarch.rpm
----
 
== Attaching the Satellite Infrastructure Subscription
After you have registered Capsule Server, you must identify your subscription Pool ID and attach an available subscription. The Red Hat Satellite Infrastructure subscription provides access to the Red Hat Satellite, Red Hat Enterprise Linux, and Red Hat Software Collections (RHSCL) content. This is the only subscription required.
[source,go]
----
# subscription-manager list --all --available --matches 'Red Hat Satellite Infrastructure Subscription'
Subscription Name:   Red Hat Satellite Infrastructure Subscription
Provides:            Red Hat Satellite
                      Red Hat Software Collections (for RHEL Server)
                      Red Hat CodeReady Linux Builder for x86_64
                      Red Hat Ansible Engine
                      Red Hat Enterprise Linux Load Balancer (for RHEL Server)
                      Red Hat
                      Red Hat Software Collections (for RHEL Server)
                      Red Hat Enterprise Linux Server
                      Red Hat Satellite Capsule
                      Red Hat Enterprise Linux for x86_64
                      Red Hat Enterprise Linux High Availability for x86_64
                      Red Hat Satellite
                      Red Hat Satellite 5 Managed DB
                      Red Hat Satellite 6
                      Red Hat Discovery
SKU:                 MCT3719
Contract:            11878983
Pool ID:             8a85f99968b92c3701694ee998cf03b8
Provides Management: No
Available:           1
Suggested:           1
Service Level:       Premium
Service Type:        L1-L3
Subscription Type:   Standard
Ends:                03/04/2020
System Type:         Physical

# subscription-manager attach --pool=8a85f99968b92c3701694ee998cf03b8
Successfully attached a subscription for: Red Hat Satellite Infrastructure Subscription

# subscription-manager list --consumed
----
 
== Configuring Repositories
 
Use this procedure to enable the repositories that are required to install Capsule Server.
 
[source,go]
----
# subscription-manager repos --disable "*"

# subscription-manager repos --enable=rhel-7-server-rpms \
--enable=rhel-7-server-satellite-capsule-6.7-rpms \
--enable=rhel-7-server-satellite-maintenance-6-rpms \
--enable=rhel-7-server-satellite-tools-6.7-rpms \
--enable=rhel-server-rhscl-7-rpms \
--enable=rhel-7-server-ansible-2.8-rpms

# yum clean all

# yum repolist enabled
 
----
 
== Installing Capsule Server Packages
 
Before installing the Capsule Server packages, you must update all packages that are installed on the base operating system.
 
[source,go]
----
# yum update -y

# yum install satellite-capsule
 
----
 
== Configuring Capsule Server with SSL Certificates
 
Red Hat Satellite uses SSL certificates to enable encrypted communications between Satellite Server, external Capsule Servers, and all hosts. Depending on the requirements of your organization, you must configure your Capsule Server with a default or custom certificate. To configure your Capsule Server with a custom SSL certificate, complete the following steps:

[source,go]
----
# katello-certs-check \
-c /root/capsule_cert/capsule_cert.pem \      
-k /root/capsule_cert/capsule_cert_key.pem \  
-b /root/capsule_cert/ca_cert_bundle.pem 
----
 ==== Example Output
[source,go]
----
Validation succeeded.

To use them inside a NEW $CAPSULE, run this command:

capsule-certs-generate --foreman-proxy-fqdn "$CAPSULE" \
    --certs-tar  "~/$CAPSULE-certs.tar" \
    --server-cert "/root/capsule_cert/capsule_cert.pem" \
    --server-key "/root/capsule_cert/capsule_cert_key.pem" \
    --server-ca-cert "/root/capsule_cert/ca_cert_bundle.pem" \

To use them inside an EXISTING $CAPSULE, run this command INSTEAD:

  capsule-certs-generate --foreman-proxy-fqdn "$CAPSULE" \
    --certs-tar  "~/$CAPSULE-certs.tar" \
    --server-cert "/root/capsule_cert/capsule_cert.pem" \
    --server-key "/root/capsule_cert/capsule_cert_key.pem" \
    --server-ca-cert "/root/capsule_cert/ca_cert_bundle.pem" \
    --certs-update-server
----
On Satellite Server, from the output of the katello-certs-check command, depending on your requirements, enter the capsule-certs-generate command that generates a certificate for a new or existing Capsule.In this command, change $CAPSULE to the FQDN of your Capsule Server.
[source,go]
----
output omitted
satellite-installer \
--scenario capsule \
--certs-tar-file                              "/root/capsule_certs.tar"\
--foreman-proxy-content-parent-fqdn           "rhsatellite01.sbcdom.com"\
--foreman-proxy-register-in-foreman           "true"\
--foreman-proxy-foreman-base-url              "https://rhsatellite01.sbcdom.com"\
--foreman-proxy-trusted-hosts                 "rhsatellite01.sbcdom.com"\
--foreman-proxy-trusted-hosts                 "capsule.example.com"\
--foreman-proxy-oauth-consumer-key            "s97QxvUAgFNAQZNGg4F9zLq2biDsxM7f"\
--foreman-proxy-oauth-consumer-secret         "6bpzAdMpRAfYaVZtaepYetomgBVQ6ehY"\
--puppet-server-foreman-url                   "https://rhsatellite01.sbcdom.com"
----
On Satellite Server, copy the certificate archive file to your Capsule Server:
[source,go]
----
# scp /root/capsule_cert/capsule.example.com-certs.tar \
root@rhcapsuledr01.sbcdom.com:/root/capsule.example.com-certs.tar
----

//== List of Relevant Playbooks and Roles

//#TODO# Add playbooks and roles
